version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  PR_Test:
    executor:
      name: win/default
    steps:
      # default shell is Powershell
      # - run:            
      #    command: $(echo powershell | Out-Host; $?) -and $(echo test | Out-Host; $?)
      #    shell: powershell.exe
      - run:
         command: echo "Job for PR"
         shell: bash.exe
  Master_Test:
    executor:
      name: win/default
    steps:
      - run:
         command: echo "Job for master"
         shell: cmd.exe

workflows:
  version: 2.1
  MergeToMaster:
    jobs:
      - Master_Test:
        filters:
            branches:
              only: master
  PRPushes:
    jobs:
      - PR_Test:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - dev
                - /user-.*/
