// <auto-generated />
namespace MovieRentalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingGenretomoviemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingGenretomoviemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202002121534408_adding Genre to movie model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
